// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmiusgpchyrgprjinouz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptaXVzZ3BjaHlyZ3Byamlub3V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NDMyNjYsImV4cCI6MjA3MTQxOTI2Nn0.NH8qOerLvPvod82Ei768ldcadB28SEfmOypZ1qXgW8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});